---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mcm-gcart
  namespace: mcm-gcart-subscription-ns
  labels:
    app: mcm-gcart-application
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mcm-gcart-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
