---
# Deployable for Deployment
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-gcart-deployable-deployment-web
  namespace: mcm-gcart-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: mcm-gcart-application
    subApp: web
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: mcm-gcart-web
      namespace: mcm-gcart-app-ns
    spec:
      selector:
        matchLabels:
          app: mcm-gcart-application
          subname: web
      replicas: 1
      template:
        metadata:
          labels:
            app: mcm-gcart-application
            subname: web
        spec:
          containers:
            - name: container-web
              image: "gandhicloud/g-app-store"
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
                - name: https
                  containerPort: 8082
              env:
              - name: GET_HOSTS_FROM
                value: dns
---
# Deployable for Route
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-gcart-deployable-service-web
  namespace: mcm-gcart-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: mcm-gcart-application
    subApp: web
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: mcm-gcart-web
      namespace: mcm-gcart-app-ns
      labels:
        app: mcm-gcart-application
        subname: web      
      annotations:
        # mcm.ibm.com/service-discovery: "{}"
    spec:
      type: NodePort
      ports:
        - name: my-http
          port: 8080
      selector:
        app: mcm-gcart-application
        subname: web
---
# Deployable for Service
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-gcart-deployable-route-web
  namespace: mcm-gcart-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: mcm-gcart-application
    subApp: web
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: mcm-gcart-web
      namespace: mcm-gcart-app-ns
      labels:
        app: mcm-gcart-application
        subname: web      
    spec:
      path: /
      to:
        kind: Service
        name: mcm-gcart-web
        weight: 100
      port:
        targetPort: my-http
  